version: '3'
services:
  api:
    image: buranbaev-ecomony
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

  web-cli:
    image: buranbaev-ecomony
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
