service: buranbaev-economy
app: sync-ever-to-db
org: maxburanbaev

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 900

functions:
  hello:
    handler: handler.sync
    events:
      - http:
          path: sync
          method: get
          cors: true
plugins:
  - serverless-plugin-typescript

