service: my-first-service
app: my-first-app
org: maxburanbaev

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 900

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
plugins:
  - serverless-plugin-typescript

