name: Node CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  pushDocker:
    name: pushDocker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls -la
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: maxburanbaev/economy
          tags: latest
